# -*- coding: utf-8 -*-
"""
Build the static prototype (GitHub Pages) FROM the Laravel kit.

The prototype used to be generated by its own Python templates, which meant
it could drift from what goes live. Now it is a snapshot of the real thing:
the Laravel app with the kit installed, its database filled the way the live
database will be after tools/apply_pack.py (tools/lab/seed.php), crawled page
by page. What sepahanfelez.lenzit.ir shows is exactly what sepahanfelez.ir
will show.

  python3 tools/export_static.py [http://127.0.0.1:8795]

Needs the lab running (tools/lab/README.md). Writes, at the repository root:
  index.html, price/, category/…, blog/…, about/, contact/, login/, register/,
  verify-phone/, user/… (demo account), 404.html
  rd/            CSS, JS, fonts, logo, the JSON the pages fetch (search, charts)
  images/, videos/   what the panel would hold (uploaded by the pack)

Every page is marked noindex, and forms are switched off with a note: this is
a demo, it has no backend.
"""
import http.cookiejar
import json
import os
import re
import shutil
import sys
import urllib.parse
import urllib.request

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE = (sys.argv[1] if len(sys.argv) > 1 else "http://127.0.0.1:8795").rstrip("/")
LAB = os.environ.get("REDESIGN_LAB", "/tmp/claude-1000/-home-ubuntu/07790c6b-3404-4a20-995e-d3888f29ab15/scratchpad/lab/app")

GENERATED = ["index.html", "404.html", "price", "category", "blog", "about", "contact", "login",
             "register", "verify-phone", "verify-register", "user", "rd", "images", "videos", "authors"]

DEMO = """<script>document.addEventListener('submit',function(e){e.preventDefault();
alert('این نسخه‌ی نمایشی است و فرم‌ها ارسال نمی‌شوند. در سایت اصلی همین فرم کار می‌کند.');},true);</script>"""


def opener(cookies=None):
    return urllib.request.build_opener(urllib.request.HTTPCookieProcessor(cookies or http.cookiejar.CookieJar()))


def fetch(op, path):
    try:
        r = op.open(BASE + urllib.parse.quote(path, safe="/?=&%#"))
        return r.status, r.read()
    except urllib.error.HTTPError as e:
        return e.code, e.read()


def out_path(url):
    u = urllib.parse.unquote(url.split("?")[0].split("#")[0]).strip("/")
    return os.path.join(ROOT, "index.html" if not u else os.path.join(u, "index.html"))


def demo_html(raw: bytes) -> bytes:
    h = raw.decode("utf-8")
    h = re.sub(r'<meta name="robots" content="[^"]*">', '<meta name="robots" content="noindex, nofollow">', h, 1)
    h = re.sub(r'<meta name="csrf-token" content="[^"]*">', '', h, 1)
    h = re.sub(r'<input type="hidden" name="_token" value="[^"]*">', '', h)
    # Laravel writes absolute links from the host it is served on; on the live
    # site that is sepahanfelez.ir, here it is the lab — make them relative.
    h = h.replace(BASE + "/", "/").replace(BASE, "/")
    esc = BASE.replace("/", "\\/")          # the same URL inside json_encode()d script
    h = h.replace(esc + "\\/", "\\/").replace(esc, "\\/")
    h = h.replace("</body>", DEMO + "\n</body>", 1)
    return h.encode("utf-8")


def write(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "wb") as fh:
        fh.write(data)


def main():
    for g in GENERATED:
        p = os.path.join(ROOT, g)
        if os.path.isdir(p):
            shutil.rmtree(p)
        elif os.path.exists(p):
            os.remove(p)

    guest = opener()
    st, raw = fetch(guest, "/rd/search-index.json")
    index = json.loads(raw)
    pages = ["/", "/price", "/category/", "/about", "/contact", "/blog", "/login", "/register", "/verify-phone"]
    pages += [r["u"] for r in index]
    seen, n = set(), 0
    for url in pages:
        key = urllib.parse.unquote(url).rstrip("/") or "/"
        if key in seen:
            continue
        seen.add(key)
        st, raw = fetch(guest, url)
        if st != 200:
            print("skip", st, url)
            continue
        write(out_path(url), demo_html(raw))
        n += 1
    st, raw = fetch(guest, "/this-page-does-not-exist")
    write(os.path.join(ROOT, "404.html"), demo_html(raw))

    # The user panel, as the lab's demo account sees it.
    member = opener()
    fetch(member, "/_lab/login/2")
    for url in ["/user/profile", "/user/orders", "/user/orders/1", "/user/address", "/user/address/create",
                "/user/tickets", "/user/ticket/1", "/user/tickets/create", "/user/guide"]:
        st, raw = fetch(member, url)
        if st == 200:
            write(out_path(url), demo_html(raw))
            n += 1

    # JSON the pages fetch: search and every chart.
    write(os.path.join(ROOT, "rd", "search-index.json"), json.dumps(index, ensure_ascii=False).encode("utf-8"))
    charts = set(re.findall(r'/rd/chart/(?:product|category)/\d+',
                            "".join(open(os.path.join(dp, f), encoding="utf-8").read()
                                    for dp, _, fs in os.walk(ROOT) if not dp.startswith(os.path.join(ROOT, ".git"))
                                    for f in fs if f == "index.html")))
    for c in sorted(charts):
        st, raw = fetch(guest, c)
        if st == 200:
            write(os.path.join(ROOT, c.lstrip("/")), raw)

    # Theme files and the media the panel would hold.
    shutil.copytree(os.path.join(LAB, "public_html", "rd"), os.path.join(ROOT, "rd"), dirs_exist_ok=True)
    # The favicon files the old theme's partial points at (public_html/assets/brand).
    fav = os.path.join(LAB, "public_html", "assets", "brand")
    for f in os.listdir(fav) if os.path.isdir(fav) else []:
        if f.startswith("favicon"):
            os.makedirs(os.path.join(ROOT, "assets", "brand"), exist_ok=True)
            shutil.copy2(os.path.join(fav, f), os.path.join(ROOT, "assets", "brand", f))
    for d in ("images", "videos"):
        src = os.path.join(LAB, "public_html", d)
        if os.path.isdir(src):
            shutil.copytree(src, os.path.join(ROOT, d), dirs_exist_ok=True)
    print(f"static prototype: {n} pages · {len(charts)} chart files · from {BASE}")


if __name__ == "__main__":
    main()
